### ISSUE TITLE
Find a solution how to pass user to docker container 

### ISSUE THREAD

**Issue by valegagge** [icub-tech-iit/docker-deployment-images#3]
While we were using the team-five deployments, we experienced some issues with file permission on file shared between the container and host.

The container has the user root and the files touched inside the container have root permission.
If we want to modify the same file outside the container, it is impossible because the file has root permission.

Therefore, in order to avoid this problem, we would like to add a user in the image or in the deployment.

TeamCode already analyzed this issue. Please see [here](https://github.com/icub-tech-iit/code/issues/656). 

**DoD**
Have the solution already tested

**Comment by MSECode** [comment]
So, summing up all the possible options regarding the ones tested in the linked issue and the ones evaluated lately, it is possible to:
1. IF an image is created without adding any specific user to it and, instead, trying to run the docker containers with a user, such as the one used in the current env, there's a problem of permissions when operating on files owned by root, as an example if we try to add lines to the `/root/.bashrc` file 
    1. In order to solve this a first option, as pointed out by the aforementioned issue, is to mount as read only volumes in the docker env the files: `etc/group`, `/etc/passwd`, `etc/shadow`, `etc/sudoers`.
  Anyway, this leads to 2 kinda issues. One is related to the fact that those files are present in an environment other than the original one, even if they are read only. Then the other problem is that in `/etc/sudoers` it is necessary to configure the option to run `sudo` commands without password for the user(s) running the docker container. Moreover, in order to run `sudo` this package should be installed in the docker image.
2. The other option is to add a specific user when building the image.
This leads to the following side problems (in my opinion, if you find other issues add them):
    1. First of all images should be modified
    2. Secondly, it should be a good idea to define a sort of default user name that is the same on all the images;
    3. Then, to make things way easier it is recommended to configure the user running the container only through the uid and gid and specifically to set for it the same uid and gid of the user running in the host env. Basically, files permissions are managed by user id and group id, so if in the host and in the docker container files are modified by user having the same values for uid and gid everything is fine. Typically this value is 1000, i.e. the first user, other than root, created on a machine. 
3. One thing that remains to do, is to create an image on top of another already existing. In the case the user will be added only on the top layer. 
Therefore, it would not be necessary to edit old images and new ones can be created on top of existing ones just for test purposes with a default known user. 
4. Last option, which is also mentioned in the issue, is to run the container as root and later modify the permission of a folder recursively for a specific user.

cc: @valegagge

**Comment by valegagge** [comment]
@MSECode 
Well done!!!! 💪

**Comment by valegagge** [comment]
I want just to report some tests I performed

I tried solution number 1, mentioned above in order to avoid changing all docker images.
I create the following deployment file

```
version: "3.7"

x-yarp-test: &yarp-test
  #image: ubuntu:focal
  image: superbuild-icubhead-test:latest
  environment:
    - YARP_FORWARD_LOG_ENABLE=1
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=${HOME}.Xauthority
  volumes:
    - "${HOME}/${YARP_CONF_PATH}:${HOME}/.config/yarp"
    - "${HOME}/workspace:${HOME}/workspace"
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:${HOME}/.Xauthority"
    - /etc/group:/etc/group:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - ${HOME}/my_projects/dockerStuff/testUID_GUID:/etc/sudoers:ro
  ports:
    - "10000:10000"
  network_mode: "host"
  privileged: true
  tty: true
  stdin_open: true
  working_dir: ${HOME}
  user: $CURR_UID:$CURR_GID
services:

  test_bis:
    <<: *yarp-test

```

and this is the `newsudoers` file

```
[sudo] password for vgaggero: 
# /etc/sudoers
#
# This file MUST be edited with the 'visudo' command as root.
#
# See the man page for details on how to write a sudoers file.
#

Defaults    env_reset

# Uncomment to allow members of group sudo to not need a password
# %sudo ALL=NOPASSWD: ALL

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL
vgaggero ALL=NOPASSWD:ALL

```




First, I faced the already mentioned issue about writing on `/root/.bashrc` file in the entrypoint.

```
vgaggero@iiticublap301u:~/my_projects/dockerStuff/testUID_GUID$ docker-compose -f deploy_user.yml up
WARNING: The YARP_CONF_PATH variable is not set. Defaulting to a blank string.
Creating testuid_guid_test_bis_1 ... done
Attaching to testuid_guid_test_bis_1
test_bis_1  | This image was built on none
test_bis_1  | /usr/local/bin/entrypoint.sh: line 11: /root/.bashrc: Permission denied
testuid_guid_test_bis_1 exited with code 1

```

Second, I tried to change the entry point by substituting `/root/.bashrc` with `${HOME}/.bashrc` 

but it doesn't work.

```
WARNING: The YARP_CONF_PATH variable is not set. Defaulting to a blank string.
Starting testuid_guid_test_bis_1 ... done
Attaching to testuid_guid_test_bis_1
test_bis_1  | This images has release=master and had been building with superbuild_tag=Unstable. Metadata=none
test_bis_1  | /usr/local/bin/entrypoint.sh: line 11: /home/vgaggero/.bashrc: Permission denied
testuid_guid_test_bis_1 exited with code 1
```

I tried to share the `bashrc` file, but I got this error when I attached to the container:
```
docker exec -it testuid_guid_test_bis_1 bash
bash: kubectl: command not found
bash: /home/vgaggero/MY_WORKSPACE/ROBOTOLOGY/robotology-superbuild/build/install/share/robotology-superbuild/setup.sh: No such file or directory
This images has release=master and had been building with superbuild_tag=Unstable. Metadata=none
This images has release=master and had been building with superbuild_tag=Unstable. Metadata=none
This images has release=master and had been building with superbuild_tag=Unstable. Metadata=none
vgaggero@iiticublap301u:~$ vgaggero@iiticublap301u:~/my_projects/dockerStuff/testUID_GUID$ 

```


We need to investigate further
